name: Build Flutter Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17' 

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Create missing platform folders
        run: flutter create .

      # YEH NAYA STEP HAI - Android version ko latest (34) par force karne ke liye
      - name: Fix Android SDK Versions
        run: |
          sed -i 's/flutter.compileSdkVersion/34/g' android/app/build.gradle
          sed -i 's/flutter.targetSdkVersion/34/g' android/app/build.gradle
          sed -i 's/flutter.minSdkVersion/24/g' android/app/build.gradle

      - name: Build APK (Release)
        run: flutter build apk --release

      - name: Upload APK to Actions Tab
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
